- hosts: localhost
  become: true
  tasks:
  - name: Install htop
    zypper: name=htop

  - name: Install vim
    zypper: name=vim

  - name: Install wireshark
    zypper: name=wireshark

  - name: Install deluge
    zypper: name=deluge


  - name: Install vlc
    zypper: name=vlc

  - name: Install nmap
    zypper: name=nmap


  - name: Install irssi
    zypper:  name=irssi

  - name: Install ssldump
    zypper: name=ssldump
  
  - name: Install tmux
    zypper: name=tmux


  - name: Install distrobox
    zypper: name=distrobox

  - name: Install gimp
    zypper: name=gimp

  - name: Install evince
    zypper: name=evince

  - name: Install Docker
    zypper: name=docker
    
  - name: Install Docker-compose
    zypper: name=docker-compose  

  - name: KVM server pattern
    zypper: name=kvm_server type=pattern

  - name: KVM tools
    zypper: name=kvm_tools type=pattern
 
  - name: vscode repo
    zypper_repository:
      repo:  https://packages.microsoft.com/yumrepos/vscode vscode 
      name: vscode
      auto_import_keys: yes

  - name: Install code
    zypper: name=code


###flatpak installs###
  - name: Installation of multiple flatpaks
    community.general.flatpak: 
      name:
        - org.signal.Signal
        - com.slack.Slack
        - org.eclipse.Java
        - org.ferdium.Ferdium
        - io.freetubeapp.FreeTube
      state: present
