- hosts: localhost
  become: true
  tasks:
  - name: Install htop
    dnf: name=htop

  - name: Install vim
    dnf: name=vim

  - name: Install wireshark
    dnf: name=wireshark

  - name: Install deluge
    dnf: name=deluge


  - name: Install vlc
    dnf: name=vlc

  - name: Install nmap
    dnf: name=nmap


  - name: Install irssi
    dnf:  name=irssi

  - name: Install ssldump
    dnf: name=ssldump
  
  - name: Install tmux
    dnf: name=tmux


  - name: Install distrobox
    dnf: name=distrobox

  - name: Install gimp
    dnf: name=gimp

  - name: Install evince
    dnf: name=evince


  - name: Install dev tools
    dnf:
      name: '@Development tools'
      state: present

  - name: Install virt env
    dnf: name=libvirt

  - name: Install virt-manager
    dnf: name=virt-manager

  - name: Install brave repo
    ansible.builtin.yum_repository:
      name: brave-browser
      baseurl: https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
      gpgcheck: yes
      gpgkey:  https://brave-browser-rpm-release.s3.brave.com/brave-core.asc

  - name: Install brave
    dnf: name=brave-browser


###flatpak installs###
  - name: Installation of multiple flatpaks
    community.general.flatpak: 
      name:
        - org.signal.Signal
        - com.slack.Slack
        - org.eclipse.Java
        - org.ferdium.Ferdium
        - io.freetubeapp.FreeTube
      state: present
