- hosts: localhost
  become: true
  tasks:
  - name: Install htop
    dnf: name=htop

  - name: Install vim
    dnf: name=vim

  - name: Install wireshark
    dnf: name=wireshark

  - name: Install deluge
    dnf: name=deluge

  - name: Install openvpn
    dnf: name=openvpn

  - name: Install vlc
    dnf: name=vlc

  - name: Install nmap
    dnf: name=nmap

  - name: Install aircrack-ng
    dnf: name=aircrack-ng

  - name: Install docker
    dnf: name=docker

  - name: Install irssi
    dnf:  name=irssi

  - name: Install ssldump
    dnf: name=ssldump
  
  - name: Install tmux
    dnf: name=tmux

  - name: Install 
    dnf: name=qemu-img

  - name: Install
    dnf: name=libvirt

  - name: Install
    dnf: name=virt-manager

  - name: Install
    dnf: name=libvirt-python

  - name: Install
    dnf: name=libvirt-client

